name: Publish
on: [push, workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Check Tag
      id: check-release-tag
      run: |
        if [[ ${{ github.event.ref }} =~ ^refs/tags/[0-9]+[.][0-9]+[.][0-9]+(rc[0-9]+|[.]dev[0-9]+)?$ ]]; then
          echo ::set-output name=release_tag::true
        fi

    - name: Publish to CodeArtifact
      if: steps.check-release-tag.outputs.release_tag == 'true'
      run: |
        aws codeartifact login --tool twine --repository shalion-python --domain shalion --domain-owner 179139584857
        pip install --upgrade setuptools wheel twine
        python setup.py sdist bdist_wheel
        twine upload --repository codeartifact dist/*
